### PR TITLE
Allow custom timeout, interval and addresses

### PR DESCRIPTION
**Pull request by jopmiddelkamp**
## Status

**READY**

## Breaking Changes

NO

## Description

Allow custom timeout, interval and addresses

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by jopmiddelkamp** [comment]
@RounakTadvi Could you review this PR?

**Comment by RounakTadvi** [comment]
@jopmiddelkamp Sure

**Review by RounakTadvi — APPROVED** [review]
LGTM thanks so much for the contribution, really appreciate it! 💙 🚀

**Comment by RounakTadvi** [comment]
LGTM thanks so much for the contribution, really appreciate it! 💙 🚀

**Pull request merged**
